### PR TITLE
AMD GPUs support with rocm-smi

### PR DESCRIPTION
**Pull request by maleksan85**
Adding support for AMD cards. Tried on my setup and getting this:
image

### CODE REVIEW

**Comment by maleksan85** [comment]
@elazarcoh please take a look. Thanks!

**Comment by elazarcoh** [comment]
From a quick scan of the code it looks pretty good! I'll go over it more thoroughly next week and merge it soon hopefully.
I don't have an AMD to test it, but it seems to work for you so I guess it's fine.

Thank you!

**Comment by maleksan85** [comment]
> From a quick scan of the code it looks pretty good! I'll go over it more thoroughly next week and merge it soon hopefully. I don't have an AMD to test it, but it seems to work for you so I guess it's fine.
> 
> Thank you!

Thank you! I don't have Nvidia :) please double check that generalization I did still works on Nvidia :)

**Comment by elazarcoh** [comment]
I've pushed a small update. would you mind check it out?
image

**Comment by elazarcoh** [comment]
Oh and one more important thing, we need to change the extension name. I'll need to check it it's possible

**Comment by elazarcoh** [comment]
> I've pushed a small update. would you mind check it out? image

@maleksan85

**Comment by maleksan85** [comment]
There might be some renaming needed saying that AMD is supported. But I believe it is better to do separate PR.

**Comment by maleksan85** [comment]
@elazarcoh please check this PR, either leave comment to improve or complete it please. I don't have rights to complete the PR to your repo.

**Comment by elazarcoh** [comment]
Hi, I've been waiting for feedback on the button I mentioned above. Is it working well for AMD?

**Comment by elazarcoh** [comment]
> I've pushed a small update. would you mind check it out?
> image
> 

This thing

**Comment by maleksan85** [comment]
Yeah, with the change you did in second commit - yep. Please see my reply some time ago:
image

**Comment by elazarcoh** [comment]
Hmm I don't see it. Probably because it says pending. Doesn't matter, I'll merge and make a release on the weekend.

**Pull request merged**
